resolver: lts-18.28

extra-deps:
- github: quanterall/qtility
  commit: dd5ea49082c6f8eff4d5d2d688afb2b9553fc4cf
  subdirs:
  - qtility
  # nix-sha256: sha256-1YJDc8R46hUeFFpoL8KmuAJTdo1jUzJap673ZLpSoYo=

nix:
  enable: false
  packages:
    - zlib
